name: Continuos Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test AHK v1.1.22.01
        uses: nukdokplex/autohotkey-build@master
        with:
          version: v1.1.22.01
          x64: true
          x86: true
          compression: upx
          in: test_scripts/v1.1
          out: outv1.1
          icon: ""
      - name: Test AHK v2.0.2
        uses: nukdokplex/autohotkey-build@master
        with:
          version: v2.0.2
          x64: true
          x86: true
          compression: upx
          in: test_scripts/v2
          out: outv2
          icon: ""
      - name: List output directories
        shell: pwsh
        run: |
          ls outv1.1
          ls outv2

